services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /healthz
