"""align schema with models

Revision ID: a1d8aae6e9fe
Revises: mrg_20250812_single_head
Create Date: 2025-08-14 11:09:50.834470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8aae6e9fe'
down_revision = 'mrg_20250812_single_head'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_index('ix_participant_event_id', table_name='participant')
    op.drop_index('ix_participant_user_id', table_name='participant')
    op.drop_table('participant')
    op.add_column('user', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_unique_constraint('uq_users_email', 'user', ['email'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False))
    op.drop_constraint('uq_users_email', 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.alter_column('user', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_column('user', 'hashed_password')
    op.create_table('participant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participant_user_id', 'participant', ['user_id'], unique=False)
    op.create_index('ix_participant_event_id', 'participant', ['event_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('required_attendees', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('is_locked_for_registration', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
